name: rich_highlight_text_codespark
description: "Adds extension methods to highlight substrings in Text or String using Text.rich and custom styles. Simple inline highlighting with minimal code."
version: 0.0.2
homepage: https://github.com/Katayath-Sai-Kiran/rich_highlight_codespark

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

assets: 
  - 'assets/screenshots/'
  - 'assets/banners/'

screenshots:

  - path: assets/screenshots/300X650-01.png
    description: "Highlighting text in a Text widget with custom styles"
    width: 300



topics:
  - text
  - highlight
  - richtext
  - inline-style
  - textspan

  
